export type RequestType = 'Pastelito de celebración'|'Pastel de boda o XV años'|'Producto para Candy Bar';
export type QuoteStatus = 'Nueva'|'Pendiente de contacto'|'Contactada'|'En negociación'|'Pendiente de pago'|'Pago verificado'|'Agendada'|'En producción'|'Entregada'|'No concretada / cancelada';
export type PaymentStatus = 'No registrado'|'Pendiente de validar'|'Validación manual';
export type DeliveryMode = 'Entrega'|'Recolección';
export type CandyItem = {name:string; quantity:number};
export type HistoryEntry = {at:string; text:string};
export type PriceBreakdown = {base:number; portions:number; customization:number; delivery:number; items:number};
export type Quote = {id:string;createdAt:string;clientName:string;phone:string;email:string;requestType:RequestType;portions:number;sizeReference:string;designType:string;designDetails:string;needsDesignHelp:boolean;referenceImage:string;eventDate:string;eventTime:string;location:string;deliveryMode:DeliveryMode;deliveryLocation:string;candyBarItems:CandyItem[];observations:string;estimatedPrice:number;priceBreakdown:PriceBreakdown;finalPrice:string;status:QuoteStatus;paymentStatus:PaymentStatus;internalNotes:string;followUpHistory:HistoryEntry[];notificationStatus:string;productionApproved:boolean;productionStatus:string;updatedAt:string;lastContact:string;responsible:string};
export type Customer = {id:string;name:string;phone:string;birthMonth:number;eventMonth:number;quoteIds:string[];orderCount:number;lastContact:string;source:string;isDemoData:boolean;status:string};
export type Notification = {id:string;quoteId:string;createdAt:string;type:string;status:string;recipientLabel:string;messagePreview:string};
export const statuses:QuoteStatus[]=['Nueva','Pendiente de contacto','Contactada','En negociación','Pendiente de pago','Pago verificado','Agendada','En producción','Entregada','No concretada / cancelada'];
export const requestTypes:RequestType[]=['Pastelito de celebración','Pastel de boda o XV años','Producto para Candy Bar'];
export const sizeReferences:Record<number,string>={10:'Aprox. 10 cm alto × 15 cm ancho · 1 capa de relleno',15:'Aprox. 14 cm alto × 15 cm ancho · 2 capas de relleno',20:'Aprox. 16 cm alto × 17 cm ancho · 2 capas de relleno',25:'Aprox. 14 cm alto × 21 cm ancho · 2 capas de relleno'};
export const business={phone:'+502 5065 5227', whatsappNumber:'50250655227', whatsappPendingVerification:true,facebook:'https://www.facebook.com/AwakeAndBakeGt/',instagram:'https://www.instagram.com/awakeandbakegt/',location:'Dentro de Café Respiro, zona 10, Ciudad de Guatemala'};
// Todos los importes salvo Q375 son provisionalDemo y editables antes de producción.
export const pricingConfig={provisionalDemo:true,confirmedFrom10:375,portionIncrement:85,weddingSupplement:180,customDesign:95,designHelp:55,deliveryReference:65,candyBase:230,candyItemUnit:28};
export function estimate(q:Pick<Quote,'requestType'|'portions'|'designType'|'deliveryMode'|'candyBarItems'>):PriceBreakdown{
 const candy=q.requestType==='Producto para Candy Bar';
 return {base:candy?pricingConfig.candyBase:pricingConfig.confirmedFrom10+(q.requestType==='Pastel de boda o XV años'?pricingConfig.weddingSupplement:0), portions:candy?0:Math.max(0,(q.portions-10)/5)*pricingConfig.portionIncrement,customization:candy?0:q.designType==='Diseño personalizado'?pricingConfig.customDesign:q.designType==='Necesito apoyo con el diseño'?pricingConfig.designHelp:0,delivery:q.deliveryMode==='Entrega'?pricingConfig.deliveryReference:0,items:candy?q.candyBarItems.reduce((sum,item)=>sum+(Number(item.quantity)||0)*pricingConfig.candyItemUnit,0):0};
}
export const total=(p:PriceBreakdown)=>Object.values(p).reduce((a,b)=>a+b,0);
export const money=(n:number)=>`Q${Math.round(n).toLocaleString('es-GT')}`;
const daysFromNow=(days:number)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
const ago=(days:number)=>{const d=new Date();d.setDate(d.getDate()-days);return d.toISOString()};
const makeDemo=(id:string,name:string,type:RequestType,status:QuoteStatus,days:number,portions:number,mode:DeliveryMode):Quote=>{const q:Quote={id,createdAt:ago(days),clientName:name,phone:'+502 5••• ••27',email:'',requestType:type,portions,sizeReference:sizeReferences[portions]||'',designType:'Tengo una idea definida',designDetails:'Referencia de diseño por confirmar con el equipo.',needsDesignHelp:false,referenceImage:'',eventDate:daysFromNow(12+days),eventTime:'11:00',location:'Ciudad de Guatemala',deliveryMode:mode,deliveryLocation:mode==='Entrega'?'Zona por confirmar':'',candyBarItems:type==='Producto para Candy Bar'?[{name:'Producto por definir',quantity:12}]:[],observations:'Datos ficticios para explorar el seguimiento.',estimatedPrice:0,priceBreakdown:{base:0,portions:0,customization:0,delivery:0,items:0},finalPrice:'',status,paymentStatus:'No registrado',internalNotes:'Confirmar detalles por contacto personal.',followUpHistory:[{at:ago(days),text:'Solicitud de demostración creada.'}],notificationStatus:'Aviso simulado',productionApproved:['Agendada','En producción','Entregada'].includes(status),productionStatus:status==='Entregada'?'Entregado':status==='En producción'?'En preparación':'Pendiente',updatedAt:ago(days),lastContact:'',responsible:'Equipo Awake & Bake'};q.priceBreakdown=estimate(q);q.estimatedPrice=total(q.priceBreakdown);return q};
export const seedQuotes:Quote[]=[makeDemo('AB-DEMO-1024','Ana Morales','Pastel de boda o XV años','Nueva',0,25,'Entrega'),makeDemo('AB-DEMO-1023','Gabriela López','Pastelito de celebración','Pendiente de contacto',2,15,'Recolección'),makeDemo('AB-DEMO-1022','Sofía Méndez','Producto para Candy Bar','En negociación',4,10,'Entrega'),makeDemo('AB-DEMO-1021','Daniel Castillo','Pastel de boda o XV años','Agendada',7,20,'Recolección')];
export const seedCustomers:Customer[]=[{id:'C-DEMO-01',name:'Ana Morales',phone:'+502 5••• ••27',birthMonth:4,eventMonth:10,quoteIds:['AB-DEMO-1024'],orderCount:0,lastContact:'',source:'Demostración',isDemoData:true,status:'Solicitud reciente'},{id:'C-DEMO-02',name:'Gabriela López',phone:'+502 4••• ••81',birthMonth:9,eventMonth:11,quoteIds:['AB-DEMO-1023'],orderCount:1,lastContact:daysFromNow(-18),source:'Demostración',isDemoData:true,status:'Sin seguimiento'},{id:'C-DEMO-03',name:'Sofía Méndez',phone:'+502 3••• ••42',birthMonth:2,eventMonth:12,quoteIds:['AB-DEMO-1022'],orderCount:0,lastContact:daysFromNow(-4),source:'Demostración',isDemoData:true,status:'En conversación'},{id:'C-DEMO-04',name:'Daniel Castillo',phone:'+502 5••• ••19',birthMonth:12,eventMonth:10,quoteIds:['AB-DEMO-1021'],orderCount:1,lastContact:daysFromNow(-2),source:'Demostración',isDemoData:true,status:'Pedido agendado'}];
export const seedNotifications:Notification[]=[{id:'N-DEMO-1',quoteId:'AB-DEMO-1024',createdAt:ago(0),type:'Correo de nueva solicitud',status:'Simulada',recipientLabel:'Equipo Awake & Bake · correo pendiente',messagePreview:'Nueva solicitud de pastel para evento recibida.'}];
const KEY='awake-bake-demo-v1';
export type Store={quotes:Quote[];customers:Customer[];notifications:Notification[]};
export function loadStore():Store{try{const raw=localStorage.getItem(KEY);if(raw){const data=JSON.parse(raw);if(Array.isArray(data.quotes))return data}}catch{}return {quotes:seedQuotes,customers:seedCustomers,notifications:seedNotifications}}
export function saveStore(data:Store){localStorage.setItem(KEY,JSON.stringify(data))}
export const formatDate=(v:string)=>v?new Date(v.includes('T')?v:`${v}T12:00:00`).toLocaleDateString('es-GT',{day:'2-digit',month:'short',year:'numeric'}):'Pendiente';
export const formatDateTime=(v:string)=>v?new Date(v).toLocaleString('es-GT',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'Sin registro';
