import {chromium} from 'playwright';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const base=process.env.QA_URL||'http://localhost:4173';
const shots='qa/progressive-2026-09-25';fs.mkdirSync(shots,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1});
const page=await context.newPage();const errors=[];
page.on('pageerror',error=>errors.push(error.message));
page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});
page.on('response',response=>{if(response.status()===404)errors.push(`404 ${response.url()}`)});
const section=index=>page.locator(`[data-quote-section="${index}"]`);
const opened=async index=>section(index).locator('.quote-section-content').waitFor();
const shot=async (name,target=page)=>{await target.waitForTimeout(440);await target.screenshot({path:`${shots}/${name}.jpg`,quality:90})};
const imageReady=async locator=>{await locator.evaluate(img=>img.decode());assert.ok(await locator.evaluate(img=>img.naturalWidth>0),'Broken image')};
await page.goto(base+'/');await imageReady(page.locator('.calm-hero img'));
await shot('hero-1440');
const start=await page.locator('.calm-hero-copy').evaluate(el=>Number(getComputedStyle(el).opacity));
await page.evaluate(()=>window.scrollTo({top:document.querySelector('.calm-hero').offsetHeight*.48,behavior:'instant'}));await page.waitForTimeout(150);
const faded=await page.locator('.calm-hero-copy').evaluate(el=>Number(getComputedStyle(el).opacity));
assert.ok(faded<start-.15,`Hero did not fade: ${start} -> ${faded}`);
await shot('hero-fade-1440');
await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(150);
assert.ok(await page.locator('.calm-hero-copy').evaluate(el=>Number(getComputedStyle(el).opacity))>.98,'Hero did not recover on upward scroll');
assert.equal(await page.locator('.cake-experience').count(),0,'Long sticky experience still rendered');
await page.goto(base+'/cotiza-tu-propio-pastel');
assert.equal(await page.getByRole('button',{name:/Continuar/}).count(),0,'Continue buttons remain');
const typeImages=[['Pastelito de celebración','celebration.webp'],['Pastel de boda o XV años','wedding.webp'],['Producto para Candy Bar','candy-bar.webp']];
for(let i=0;i<typeImages.length;i++){
 const [type,file]=typeImages[i];if(i)await section(0).locator('.quote-section-head').click();
 await section(0).getByRole('button',{name:new RegExp(type)}).click();await opened(1);
 const src=await section(1).locator('.quote-selected-photo img').getAttribute('src');assert.ok(src.endsWith(file),`${type}: ${src}`);
 await imageReady(section(1).locator('.quote-selected-photo img'));
}
await section(0).locator('.quote-section-head').click();await section(0).getByRole('button',{name:/Pastelito de celebración/}).click();await opened(1);
await shot('quote-selected-1440');
await section(1).getByPlaceholder('Tu nombre y apellido').fill('Prueba QA');
await section(1).getByPlaceholder('nombre@ejemplo.com').fill('qa@example.test');
await section(1).getByPlaceholder('+502 0000 0000').fill('+502 5555 0101');await opened(2);
const previews=[[10,'celebration.webp','Q375','1 capa de relleno'],[15,'custom-design.webp','Q460','2 capas de relleno'],[20,'design-help.webp','Q545','2 capas de relleno'],[25,'closing.webp','Q630','2 capas de relleno']];
for(const [count,file,total,layers] of previews){
 if(count!==10)await section(2).locator('.quote-section-head').click();
 await section(2).getByRole('button',{name:new RegExp(`${count} porciones`)}).click();await opened(3);
 assert.ok((await section(3).locator('.quote-current-portion img').getAttribute('src')).endsWith(file),`${count}: wrong preview`);
 assert.ok((await section(3).locator('.quote-current-portion').innerText()).includes(layers),`${count}: wrong layers`);
 assert.equal(await page.locator('.aside-price').innerText(),total,`${count}: wrong price`);
 assert.ok((await page.locator('.quote-live-summary').innerText()).includes(`${count} porciones`),`${count}: stale summary`);
 if(count===10||count===20)await shot(`portion-${count}-1440`);
}
await section(2).locator('.quote-section-head').click();await section(2).getByRole('button',{name:/15 porciones/}).click();await opened(3);
await section(3).locator('input[type=file]').setInputFiles({name:'referencia.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/c6sAAAAASUVORK5CYII=','base64')});await opened(4);
const future=new Date();future.setDate(future.getDate()+22);await section(4).locator('input[type=date]').fill(future.toISOString().slice(0,10));await section(4).locator('input[type=time]').fill('14:00');await section(4).getByPlaceholder('Zona y ciudad').fill('Zona 10, Ciudad de Guatemala');await opened(5);
await section(5).getByRole('button',{name:'Entrega',exact:true}).click();assert.ok(await section(5).locator('.quote-section-content').isVisible(),'Delivery address skipped');
await section(5).getByPlaceholder('Dirección o zona de entrega').fill('Zona 10');await section(5).getByPlaceholder('Algo más que debamos saber...').fill('Sin nueces');await opened(6);
assert.equal(await page.locator('.aside-price').innerText(),'Q525');
await shot('quote-progress-1440');
await section(6).getByRole('button',{name:/Revisar solicitud/}).click();await opened(7);await section(7).getByText('Sin nueces').waitFor();await section(7).locator('.review-image').waitFor();
// Edit an earlier choice without losing the later fields or uploaded reference.
await section(2).locator('.quote-section-head').click();await section(2).getByRole('button',{name:/20 porciones/}).click();await opened(3);
await section(7).locator('.quote-section-head').click();await opened(7);assert.equal(await page.locator('.aside-price').innerText(),'Q610');assert.ok(await section(7).locator('.review-image').isVisible());await section(7).getByText('Sin nueces').waitFor();
await section(7).locator('.accept input').check();await section(7).getByRole('button',{name:/Enviar solicitud/}).click();
const id=(await page.locator('.success-card strong').innerText()).trim();assert.ok(id.startsWith('AB-'));await page.goto(base+'/admin');await page.getByText('Avisos de correo simulados').waitFor();await page.getByText('Nueva solicitud de Prueba QA').waitFor();await shot('crm-after-quote-1440');
await page.goto(base+'/admin/cotizaciones');await page.getByText(id).first().click();await page.locator('.quote-modal').waitFor();await page.locator('.reference-large img').waitFor();assert.equal(await page.locator('.detail-hero strong').innerText(),'Q610');
await page.evaluate(()=>{window.open=url=>{window.__qaWhatsapp=url;return null}});await page.getByRole('button',{name:/Contactar por WhatsApp/}).click();const whatsapp=await page.evaluate(()=>window.__qaWhatsapp);assert.ok(whatsapp.includes(id)&&whatsapp.includes('Prueba'),'WhatsApp link lost quote details');
await page.locator('.admin-fields select').first().selectOption('Pendiente de contacto');await page.locator('.admin-fields input[type=number]').fill('650');await page.getByPlaceholder('Detalles para el equipo').fill('Confirmar colores');await page.getByPlaceholder('Ej. se llamó para confirmar disponibilidad').fill('Intento de llamada QA');await page.getByRole('button',{name:/Guardar cambios/}).click();await page.getByRole('button',{name:/Historial/}).click();await page.getByText('Intento de llamada QA').waitFor();await page.getByRole('button',{name:'Cerrar'}).click();
await page.getByRole('button',{name:'Pendientes de contacto'}).click();assert.ok(await page.getByText(id).count()>0,'Filter lost quote');await page.getByText(id).first().click();await page.locator('.admin-fields select').first().selectOption('En producción');await page.locator('.approval input').check();await page.getByRole('button',{name:/Guardar cambios/}).click();await page.getByRole('button',{name:'Cerrar'}).click();
await page.goto(base+'/admin/produccion');const production=page.locator('.production-card').filter({hasText:id});await production.waitFor();await production.getByRole('button',{name:/Marcar entregado/}).click();await production.getByText('Entregado').waitFor();
await page.goto(base+'/admin/clientes');await page.getByPlaceholder('Buscar por nombre').fill('Ana');assert.equal(await page.locator('.customer-card').count(),1);
await page.goto(base+'/productos');await page.locator('.catalog-grid img').first().evaluate(img=>img.decode());
// Candy Bar follows the same saved model and advances after its product group is complete.
const candy=await context.newPage();candy.on('pageerror',error=>errors.push(error.message));await candy.goto(base+'/cotiza-tu-propio-pastel');const candySection=index=>candy.locator(`[data-quote-section="${index}"]`);await candySection(0).getByRole('button',{name:/Producto para Candy Bar/}).click();await candySection(1).locator('.quote-section-content').waitFor();await candySection(1).getByPlaceholder('Tu nombre y apellido').fill('Candy QA');await candySection(1).getByPlaceholder('+502 0000 0000').fill('+502 5555 0102');await candySection(2).locator('.quote-section-content').waitFor();await candySection(2).getByPlaceholder('Ej. producto para mesa dulce').fill('Macarons');const firstPrice=await candy.locator('.aside-price').innerText();await candySection(2).getByRole('button',{name:/Agregar producto/}).click();await candySection(2).getByPlaceholder('Ej. producto para mesa dulce').nth(1).fill('Cupcakes');const secondPrice=await candy.locator('.aside-price').innerText();assert.notEqual(firstPrice,secondPrice);await candySection(3).locator('.quote-section-content').waitFor();await candySection(3).getByRole('button',{name:'Necesito apoyo con el diseño'}).click();await candySection(4).locator('.quote-section-content').waitFor();await candy.close();
const mobile=await browser.newContext({viewport:{width:390,height:850},reducedMotion:'reduce'});const mobilePage=await mobile.newPage();await mobilePage.goto(base+'/');await shot('hero-390',mobilePage);assert.equal(await mobilePage.locator('.calm-hero-visual').evaluate(el=>getComputedStyle(el).transform),'none');await mobilePage.goto(base+'/cotiza-tu-propio-pastel');await mobilePage.locator('.type-card').first().click();await mobilePage.locator('[data-quote-section="1"] .quote-section-content').waitFor();assert.equal(await mobilePage.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await shot('quote-selected-390',mobilePage);
const mobileSection=index=>mobilePage.locator(`[data-quote-section=\"${index}\"]`);
await mobileSection(1).getByPlaceholder('Tu nombre y apellido').fill('Móvil QA');
await mobileSection(1).getByPlaceholder('+502 0000 0000').fill('+502 5555 0103');
await mobileSection(2).locator('.quote-section-content').waitFor();
await mobileSection(2).getByRole('button',{name:/10 porciones/}).click();
await mobileSection(3).locator('.quote-section-content').waitFor();await mobileSection(3).evaluate(el=>window.scrollTo({top:window.scrollY+el.getBoundingClientRect().top-82,behavior:'instant'}));await shot('portion-10-390',mobilePage);
await mobileSection(3).getByPlaceholder('Cuéntanos cómo imaginas tu pastel...').fill('Flores rosadas');
await mobileSection(3).locator('textarea').evaluate(el=>el.blur());
await mobileSection(4).locator('.quote-section-content').waitFor();
await mobileSection(4).locator('input[type=date]').fill(future.toISOString().slice(0,10));
await mobileSection(4).locator('input[type=time]').fill('10:00');
await mobileSection(4).getByPlaceholder('Zona y ciudad').fill('Zona 10');
await mobileSection(5).locator('.quote-section-content').waitFor();
await mobileSection(5).getByRole('button',{name:'Recolección',exact:true}).click();
await mobileSection(6).locator('.quote-section-content').waitFor();
await mobileSection(6).getByRole('button',{name:/Revisar solicitud/}).click();
await mobileSection(7).locator('.quote-section-content').waitFor();
await mobileSection(7).locator('.accept input').check();
await mobileSection(7).getByRole('button',{name:/Enviar solicitud/}).click();
const mobileId=(await mobilePage.locator('.success-card strong').innerText()).trim();
await mobilePage.goto(base+'/admin/cotizaciones');await mobilePage.getByText(mobileId).first().waitFor();
assert.equal(await mobilePage.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await mobile.close();
await browser.close();assert.deepEqual(errors,[]);console.log(JSON.stringify({savedId:id,mobileId,portionPrices:previews.map(([count,,total])=>`${count}: ${total}`),finalEstimate:'Q610',candyPrices:[firstPrice,secondPrice],heroFade:[start,faded],routesVerified:7,errors},null,2));
