import {chromium} from 'playwright';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const base=process.env.QA_URL||'http://localhost:4173';
const shots=process.env.QA_SHOTS||'qa/updated-2026-09-28/functional';fs.mkdirSync(shots,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1});
const page=await context.newPage();const errors=[];
page.on('pageerror',error=>errors.push(error.message));
page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});
page.on('response',response=>{if(response.status()===404)errors.push(`404 ${response.url()}`)});
const section=index=>page.locator(`[data-quote-section="${index}"]`);
const opened=async index=>section(index).locator('.quote-section-content').waitFor();
const shot=async (name,target=page)=>{await target.waitForTimeout(440);await target.screenshot({path:`${shots}/${name}.jpg`,quality:90})};
const imageReady=async locator=>{await locator.evaluate(img=>img.decode());assert.ok(await locator.evaluate(img=>img.naturalWidth>0),'Broken image')};
await page.goto(base+'/');await imageReady(page.locator('.calm-hero img'));
await shot('hero-1440');
const start=await page.locator('.calm-hero-copy').evaluate(el=>Number(getComputedStyle(el).opacity));
await page.evaluate(()=>window.scrollTo({top:document.querySelector('.calm-hero').offsetHeight*.48,behavior:'instant'}));await page.waitForTimeout(150);
const faded=await page.locator('.calm-hero-copy').evaluate(el=>Number(getComputedStyle(el).opacity));
assert.ok(Math.abs(faded-start)<.01,`Hero opacity changed on scroll: ${start} -> ${faded}`);
await shot('hero-scroll-static-1440');
await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(150);
assert.ok(await page.locator('.calm-hero-copy').evaluate(el=>Number(getComputedStyle(el).opacity))>.98,'Hero lost opacity');
assert.equal(await page.locator('.cake-experience').count(),0,'Long sticky experience still rendered');
await page.goto(base+'/cotiza-tu-propio-pastel');
assert.equal(await page.getByRole('button',{name:/Continuar/}).count(),0,'Continue buttons remain');
for(let index=0;index<8;index++){
 const header=section(index).locator('.quote-section-head');
 if(index!==0)await header.click();
 assert.equal(await header.getAttribute('aria-expanded'),'true',`Section ${index} did not open`);
 await header.click();
 assert.equal(await header.getAttribute('aria-expanded'),'false',`Section ${index} did not close`);
}
await section(0).locator('.quote-section-head').click();
const typeImages=[['Pastelito de celebración','celebration.webp'],['Pastel de boda o XV años','wedding.webp'],['Producto para Candy Bar','candy-bar.webp']];
for(let i=0;i<typeImages.length;i++){
 const [type,file]=typeImages[i];if(i)await page.goto(base+'/cotiza-tu-propio-pastel');
 await section(0).getByRole('button',{name:new RegExp(type)}).click();await section(1).locator('.quote-section-head').click();await opened(1);
 const src=await section(1).locator('.quote-selected-photo img').getAttribute('src');assert.ok(src.endsWith(file),`${type}: ${src}`);
 await imageReady(section(1).locator('.quote-selected-photo img'));
}
await page.goto(base+'/cotiza-tu-propio-pastel');await section(0).getByRole('button',{name:/Pastelito de celebración/}).click();await section(1).locator('.quote-section-head').click();await opened(1);
await shot('quote-selected-1440');
await section(1).getByPlaceholder('Tu nombre y apellido').fill('Prueba QA');
await section(1).getByPlaceholder('nombre@ejemplo.com').fill('qa@example.test');
await section(1).getByPlaceholder('+502 0000 0000').fill('+502 5555 0101');await section(2).locator('.quote-section-head').click();await opened(2);
const previews=[[10,'celebration.webp','Q375','1 capa de relleno','10 cm alto × 15 cm ancho'],[15,'custom-design.webp','Q460','2 capas de relleno','14 cm alto × 15 cm ancho'],[20,'design-help.webp','Q545','2 capas de relleno','16 cm alto × 17 cm ancho'],[25,'closing.webp','Q630','2 capas de relleno','14 cm alto × 21 cm ancho']];
const portionImage=section(2).locator('.quote-portion-preview img');
const portionText=section(2).locator('.quote-portion-preview');
for(const [count,file,,layers,dimensions] of previews){
 const option=section(2).locator('.portion-options').getByRole('button',{name:new RegExp(`${count} porciones`)});
 await option.hover();
 assert.ok((await portionImage.getAttribute('src')).endsWith(file),`${count}: hover image`);
 assert.ok((await portionText.innerText()).includes(`${count} porciones`),`${count}: hover label`);
 assert.ok((await portionText.innerText()).includes(layers),`${count}: hover layers`);
 assert.ok((await portionText.innerText()).includes(dimensions),`${count}: hover dimensions`);
 assert.equal(await page.locator('.aside-price').innerText(),'Q375',`${count}: hover changed price`);
 assert.ok((await page.locator('.quote-live-summary').innerText()).includes('Pendiente'),`${count}: hover changed summary`);
 assert.equal(await option.getAttribute('aria-pressed'),'false',`${count}: hover selected option`);
 await page.locator('.quote-intro').hover();
 assert.ok((await portionImage.getAttribute('src')).endsWith('celebration.webp'),`${count}: mouse leave did not restore default`);
}
for(const [count,file,total,layers] of previews){
 await section(2).locator('.portion-options').getByRole('button',{name:new RegExp(`${count} porciones`)}).click();
 assert.ok(await section(2).locator('.quote-section-content').isVisible(),`${count}: portion section closed`);
 assert.ok((await section(2).locator('.quote-portion-preview img').getAttribute('src')).endsWith(file),`${count}: wrong preview`);
 assert.ok((await section(2).locator('.quote-portion-preview').innerText()).includes(layers),`${count}: wrong layers`);
 assert.equal(await page.locator('.aside-price').innerText(),total,`${count}: wrong price`);
 assert.ok((await page.locator('.quote-live-summary').innerText()).includes(`${count} porciones`),`${count}: stale summary`);
 if(count===10||count===20)await shot(`portion-${count}-1440`);
}
await section(2).locator('.portion-options').getByRole('button',{name:/15 porciones/}).click();
const portionScroll=await page.evaluate(()=>scrollY);
await page.waitForTimeout(250);
assert.equal(await page.evaluate(()=>scrollY),portionScroll,'Selecting portions triggered scroll');
assert.ok(await section(2).locator('.portion-options').getByRole('button',{name:/15 porciones/}).evaluate(el=>document.activeElement===el),'Selecting portions moved focus');
await section(2).locator('.portion-options').getByRole('button',{name:/25 porciones/}).hover();
assert.ok((await portionImage.getAttribute('src')).endsWith('closing.webp'),'Hover after selection did not preview');
await page.locator('.quote-intro').hover();
assert.ok((await portionImage.getAttribute('src')).endsWith('custom-design.webp'),'Mouse leave did not restore selected portion');
assert.equal(await page.locator('.aside-price').innerText(),'Q460','Hover after selection changed price');
await section(2).locator('.portion-options').getByRole('button',{name:/25 porciones/}).focus();
assert.ok((await portionImage.getAttribute('src')).endsWith('closing.webp'),'Keyboard focus did not preview');
assert.equal(await page.locator('.aside-price').innerText(),'Q460','Keyboard focus changed price');
await page.keyboard.press('Tab');
assert.ok((await portionImage.getAttribute('src')).endsWith('custom-design.webp'),'Keyboard blur did not restore selection');
await section(2).locator('.portion-options').getByRole('button',{name:/20 porciones/}).focus();await page.keyboard.press('Enter');
assert.equal(await page.locator('.aside-price').innerText(),'Q545','Keyboard selection did not confirm');
assert.ok(await section(2).locator('.quote-section-content').isVisible(),'Keyboard selection closed portions');
await section(2).locator('.portion-options').getByRole('button',{name:/15 porciones/}).click();
await section(1).locator('.quote-section-head').click();await opened(1);
await page.waitForTimeout(1300);
assert.ok(await section(1).locator('.quote-section-content').isVisible(),'Manual contact section closed after timer');
await section(1).getByPlaceholder('Tu nombre y apellido').fill('Prueba QA');
const contactScroll=await page.evaluate(()=>scrollY);
await page.waitForTimeout(1300);
assert.ok(await section(1).locator('.quote-section-content').isVisible(),'Manual contact edit was overridden');
assert.equal(await page.evaluate(()=>scrollY),contactScroll,'Manual contact edit triggered scroll');
assert.ok(await section(1).getByPlaceholder('Tu nombre y apellido').evaluate(el=>document.activeElement===el),'Manual contact edit lost focus');
await section(3).locator('.quote-section-head').click();await opened(3);
await section(1).locator('.quote-section-head').click();await opened(1);await page.waitForTimeout(1100);
assert.ok(await section(1).locator('.quote-section-content').isVisible(),'Returning to contact was overridden');
await section(2).locator('.quote-section-head').click();await opened(2);await page.waitForTimeout(1100);
assert.ok(await section(2).locator('.quote-section-content').isVisible(),'Returning to portions was overridden');
await section(3).locator('.quote-section-head').click();await opened(3);
await section(3).locator('input[type=file]').setInputFiles({name:'referencia.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/c6sAAAAASUVORK5CYII=','base64')});await section(4).locator('.quote-section-head').click();await opened(4);
const future=new Date();future.setDate(future.getDate()+22);await section(4).locator('input[type=date]').fill(future.toISOString().slice(0,10));await section(4).locator('input[type=time]').fill('14:00');await section(4).getByPlaceholder('Zona y ciudad').fill('Zona 10, Ciudad de Guatemala');await section(5).locator('.quote-section-head').click();await opened(5);
await section(5).getByRole('button',{name:'Entrega',exact:true}).click();assert.ok(await section(5).locator('.quote-section-content').isVisible(),'Delivery address skipped');
await section(6).locator('.quote-section-head').click();await opened(6);await section(6).getByRole('button',{name:/Revisar solicitud/}).click();await opened(5);
for(const message of ['Indica el departamento de entrega.','Indica el municipio de entrega.','Indica la dirección exacta y número de entrega.'])await section(5).getByText(message).waitFor();
await section(5).getByPlaceholder('Ej. Guatemala').fill('Guatemala');
await section(5).getByPlaceholder('Ej. Villa Nueva').fill('Villa Nueva');
await section(5).getByPlaceholder('Ej. 2').fill('10');
await section(5).getByPlaceholder('Ej. Monte María').fill('Las Margaritas');
await section(5).getByPlaceholder('Ej. 5a calle').fill('5a calle');
await section(5).getByPlaceholder('Ej. 10a avenida').fill('10a avenida');
await section(5).getByPlaceholder('Casa, lote, edificio y número').fill('Casa 12');
await section(5).getByPlaceholder('Portón, color de casa o punto de referencia').fill('Portón café');
await section(5).getByRole('button',{name:'Recolección',exact:true}).click();assert.equal(await section(5).getByPlaceholder('Ej. Guatemala').count(),0);assert.equal(await page.locator('.aside-price').innerText(),'Q460');
await section(5).getByRole('button',{name:'Entrega',exact:true}).click();assert.equal(await section(5).getByPlaceholder('Casa, lote, edificio y número').inputValue(),'Casa 12');
await section(5).getByPlaceholder('Algo más que debamos saber...').fill('Sin nueces');await section(6).locator('.quote-section-head').click();await opened(6);
assert.equal(await page.locator('.aside-price').innerText(),'Q525');
await shot('quote-progress-1440');
await section(6).getByRole('button',{name:/Revisar solicitud/}).click();await opened(7);await section(7).getByText('Sin nueces').waitFor();await section(7).getByText(/5a calle, 10a avenida, Casa 12, Las Margaritas, Zona 10, Villa Nueva, Guatemala, Referencia: Portón café/).waitFor();await section(7).locator('.review-image').waitFor();
// Edit an earlier choice without losing the later fields or uploaded reference.
await section(2).locator('.quote-section-head').click();await section(2).locator('.portion-options').getByRole('button',{name:/20 porciones/}).click();assert.ok(await section(2).locator('.quote-section-content').isVisible());
await section(7).locator('.quote-section-head').click();await opened(7);assert.equal(await page.locator('.aside-price').innerText(),'Q610');assert.ok(await section(7).locator('.review-image').isVisible());await section(7).getByText('Sin nueces').waitFor();
await section(7).locator('.accept input').check();await section(7).getByRole('button',{name:/Enviar solicitud/}).click();
const id=(await page.locator('.success-card strong').innerText()).trim();assert.ok(id.startsWith('AB-'));await page.goto(base+'/admin');await page.getByText('Avisos de correo simulados').waitFor();await page.getByText('Nueva solicitud de Prueba QA').waitFor();await shot('crm-after-quote-1440');
await page.goto(base+'/admin/cotizaciones');await page.getByText(id).first().click();await page.locator('.quote-modal').waitFor();await page.locator('.reference-large img').waitFor();assert.equal(await page.locator('.detail-hero strong').innerText(),'Q610');await page.locator('.detail-hero').getByText(/Casa 12, Las Margaritas, Zona 10, Villa Nueva, Guatemala/).waitFor();
await page.evaluate(()=>{window.open=url=>{window.__qaWhatsapp=url;return null}});await page.getByRole('button',{name:/Contactar por WhatsApp/}).click();const whatsapp=await page.evaluate(()=>window.__qaWhatsapp);assert.ok(whatsapp.includes(id)&&whatsapp.includes('Prueba'),'WhatsApp link lost quote details');
await page.locator('.admin-fields select').first().selectOption('Pendiente de contacto');await page.locator('.admin-fields input[type=number]').fill('650');await page.getByPlaceholder('Detalles para el equipo').fill('Confirmar colores');await page.getByPlaceholder('Ej. se llamó para confirmar disponibilidad').fill('Intento de llamada QA');await page.getByRole('button',{name:/Guardar cambios/}).click();await page.getByRole('button',{name:/Historial/}).click();await page.getByText('Intento de llamada QA').waitFor();await page.getByRole('button',{name:'Cerrar'}).click();
await page.getByRole('button',{name:'Pendientes de contacto'}).click();assert.ok(await page.getByText(id).count()>0,'Filter lost quote');await page.getByText(id).first().click();await page.locator('.admin-fields select').first().selectOption('En producción');await page.locator('.approval input').check();await page.getByRole('button',{name:/Guardar cambios/}).click();await page.getByRole('button',{name:'Cerrar'}).click();
await page.goto(base+'/admin/produccion');const production=page.locator('.production-card').filter({hasText:id});await production.waitFor();await production.getByRole('button',{name:/Marcar entregado/}).click();await production.getByText('Entregado').waitFor();
await page.goto(base+'/admin/clientes');await page.getByPlaceholder('Buscar por nombre').fill('Ana');assert.equal(await page.locator('.customer-card').count(),1);
await page.goto(base+'/productos');await page.locator('.catalog-grid img').first().evaluate(img=>img.decode());
// Candy Bar follows the same saved model and advances after its product group is complete.
const candy=await context.newPage();candy.on('pageerror',error=>errors.push(error.message));candy.on('console',message=>{if(message.type()==='error')errors.push(message.text())});candy.on('response',response=>{if(response.status()===404)errors.push(`404 ${response.url()}`)});await candy.goto(base+'/cotiza-tu-propio-pastel');const candySection=index=>candy.locator(`[data-quote-section="${index}"]`);await candySection(0).getByRole('button',{name:/Producto para Candy Bar/}).click();await candySection(1).locator('.quote-section-head').click();await candySection(1).locator('.quote-section-content').waitFor();await candySection(1).getByPlaceholder('Tu nombre y apellido').fill('Candy QA');await candySection(1).getByPlaceholder('+502 0000 0000').fill('+502 5555 0102');await candySection(2).locator('.quote-section-head').click();await candySection(2).locator('.quote-section-content').waitFor();await candySection(2).getByPlaceholder('Ej. producto para mesa dulce').fill('Macarons');const firstPrice=await candy.locator('.aside-price').innerText();await candySection(2).getByRole('button',{name:/Agregar producto/}).click();await candySection(2).getByPlaceholder('Ej. producto para mesa dulce').nth(1).fill('Cupcakes');const secondPrice=await candy.locator('.aside-price').innerText();assert.notEqual(firstPrice,secondPrice);await candySection(3).locator('.quote-section-head').click();await candySection(3).locator('.quote-section-content').waitFor();await candySection(3).getByRole('button',{name:'Necesito apoyo con el diseño'}).click();await candySection(4).locator('.quote-section-head').click();await candySection(4).locator('.quote-section-content').waitFor();await candy.close();
const mobile=await browser.newContext({viewport:{width:390,height:850},isMobile:true,hasTouch:true,reducedMotion:'reduce'});const mobilePage=await mobile.newPage();mobilePage.on('pageerror',error=>errors.push(error.message));mobilePage.on('console',message=>{if(message.type()==='error')errors.push(message.text())});mobilePage.on('response',response=>{if(response.status()===404)errors.push(`404 ${response.url()}`)});await mobilePage.goto(base+'/');await shot('hero-390',mobilePage);assert.equal(await mobilePage.locator('.calm-hero-visual').evaluate(el=>getComputedStyle(el).transform),'none');await mobilePage.goto(base+'/cotiza-tu-propio-pastel');await mobilePage.locator('.type-card').first().tap();await mobilePage.locator('[data-quote-section="1"] .quote-section-head').click();await mobilePage.locator('[data-quote-section="1"] .quote-section-content').waitFor();assert.equal(await mobilePage.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await shot('quote-selected-390',mobilePage);
const mobileSection=index=>mobilePage.locator(`[data-quote-section=\"${index}\"]`);
await mobileSection(1).getByPlaceholder('Tu nombre y apellido').fill('Móvil QA');
await mobileSection(1).getByPlaceholder('+502 0000 0000').fill('+502 5555 0103');
await mobileSection(2).locator('.quote-section-head').click();await mobileSection(2).locator('.quote-section-content').waitFor();
await mobileSection(2).locator('.portion-options').getByRole('button',{name:/20 porciones/}).tap();
assert.equal(await mobilePage.locator('.aside-price').innerText(),'Q545','Touch did not confirm portions');
assert.ok(await mobileSection(2).locator('.quote-section-content').isVisible(),'Touch closed portions');
assert.ok((await mobileSection(2).locator('.quote-portion-preview img').getAttribute('src')).endsWith('design-help.webp'),'Touch preview failed');
await mobileSection(2).locator('.portion-options').getByRole('button',{name:/10 porciones/}).tap();
assert.ok(await mobileSection(2).locator('.quote-section-content').isVisible());await mobileSection(3).locator('.quote-section-head').click();await mobileSection(3).locator('.quote-section-content').waitFor();await mobileSection(3).evaluate(el=>window.scrollTo({top:window.scrollY+el.getBoundingClientRect().top-82,behavior:'instant'}));await shot('portion-10-390',mobilePage);
await mobileSection(3).getByPlaceholder('Cuéntanos cómo imaginas tu pastel...').fill('Flores rosadas');
await mobileSection(3).locator('textarea').evaluate(el=>el.blur());
await mobileSection(4).locator('.quote-section-head').click();await mobileSection(4).locator('.quote-section-content').waitFor();
await mobileSection(4).locator('input[type=date]').fill(future.toISOString().slice(0,10));
await mobileSection(4).locator('input[type=time]').fill('10:00');
await mobileSection(4).getByPlaceholder('Zona y ciudad').fill('Zona 10');
await mobileSection(5).locator('.quote-section-head').click();await mobileSection(5).locator('.quote-section-content').waitFor();
await mobileSection(5).getByRole('button',{name:'Recolección',exact:true}).click();
await mobileSection(6).locator('.quote-section-head').click();await mobileSection(6).locator('.quote-section-content').waitFor();
await mobileSection(6).getByRole('button',{name:/Revisar solicitud/}).click();
await mobileSection(7).locator('.quote-section-content').waitFor();
await mobileSection(7).locator('.accept input').check();
await mobileSection(7).getByRole('button',{name:/Enviar solicitud/}).click();
const mobileId=(await mobilePage.locator('.success-card strong').innerText()).trim();
await mobilePage.goto(base+'/admin/cotizaciones');await mobilePage.getByText(mobileId).first().waitFor();
assert.equal(await mobilePage.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await mobile.close();
await browser.close();assert.deepEqual(errors,[]);console.log(JSON.stringify({savedId:id,mobileId,portionPrices:previews.map(([count,,total])=>`${count}: ${total}`),finalEstimate:'Q610',candyPrices:[firstPrice,secondPrice],heroOpacity:[start,faded],routesVerified:7,errors},null,2));
