import {chromium} from 'playwright';
import fs from 'node:fs';
const base='http://localhost:4173';
const routes=['/','/productos','/cotiza-tu-propio-pastel','/admin','/admin/cotizaciones','/admin/clientes','/admin/produccion'];
const captures='qa/updated-2026-09-28/visual';fs.mkdirSync(captures,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
const errors=[];
const scrollAll=async(page)=>{const height=await page.evaluate(()=>document.documentElement.scrollHeight);for(let y=0;y<height;y+=520){await page.evaluate(v=>window.scrollTo(0,v),y);await page.waitForTimeout(55)}await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(320)};
for(const width of [360,390,768,1024,1440]){
 const context=await browser.newContext({viewport:{width,height:850},deviceScaleFactor:1});const page=await context.newPage();
 page.on('pageerror',error=>errors.push(`${width}: ${error.message}`));page.on('console',message=>{if(message.type()==='error')errors.push(`${width}: ${message.text()}`)});
 for(const route of routes){const response=await page.goto(base+route);if(response.status()!==200)errors.push(`${width} ${route}: HTTP ${response.status()}`);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))errors.push(`${width} ${route}: horizontal overflow`);if(!await page.locator('h1').first().isVisible())errors.push(`${width} ${route}: heading missing`);if(!await page.locator('.brand-logo').first().evaluate(img=>img.complete&&img.naturalWidth===100))errors.push(`${width} ${route}: original logo did not load`)}
 for(const [route,name] of [['/','home'],['/productos','products']]){await page.goto(base+route);await scrollAll(page);if(route==='/'){await page.locator('.photo-gallery').scrollIntoViewIfNeeded();await page.locator('.photo-gallery').evaluate(el=>el.scrollLeft=el.scrollWidth);await page.waitForTimeout(320);await page.locator('.photo-gallery').evaluate(el=>el.scrollLeft=0);await page.evaluate(()=>window.scrollTo(0,0))}const missing=await page.locator('main img').evaluateAll(images=>images.filter(img=>!img.complete||img.naturalWidth===0).map(img=>img.getAttribute('src')));if(missing.length)errors.push(`${width} ${route}: broken images ${missing.join(',')}`);if([390,1440].includes(width))await page.screenshot({path:`${captures}/${name}-${width}.png`,fullPage:true})}
 if([390,1440].includes(width)){await page.goto(base+'/');await page.locator('.gallery-tile').first().scrollIntoViewIfNeeded();await page.locator('.gallery-tile').first().click();const dialog=page.getByRole('dialog',{name:/Imagen 1 de 6/});await dialog.waitFor();await page.waitForTimeout(380);await page.screenshot({path:`${captures}/lightbox-${width}.png`});await page.keyboard.press('ArrowRight');if(!await page.getByRole('dialog',{name:/Imagen 2 de 6/}).isVisible())errors.push(`${width}: arrow navigation failed`);await page.getByRole('button',{name:'Imagen siguiente'}).click();if(!await page.getByRole('dialog',{name:/Imagen 3 de 6/}).isVisible())errors.push(`${width}: next control failed`);await page.keyboard.press('Escape');await page.waitForTimeout(60);if(await page.getByRole('dialog').count())errors.push(`${width}: Escape did not close lightbox`);const focused=await page.evaluate(()=>document.activeElement?.getAttribute('aria-label'));if(!focused?.includes('Ampliar imagen'))errors.push(`${width}: focus not restored`)}
 await context.close();
}
const reduced=await browser.newContext({viewport:{width:390,height:850},reducedMotion:'reduce'});const reducedPage=await reduced.newPage();await reducedPage.goto(base+'/');const motion=await reducedPage.locator('[data-reveal]').first().evaluate(el=>({opacity:getComputedStyle(el).opacity,duration:getComputedStyle(el).transitionDuration}));if(motion.opacity!=='1'||motion.duration!=='0s')errors.push(`reduced motion failed: ${JSON.stringify(motion)}`);await reduced.close();
const page=await browser.newPage();await page.goto(base+'/');const photos=await page.locator('main img').evaluateAll(images=>images.map(img=>({src:img.getAttribute('src'),alt:img.alt,loading:img.loading,fit:getComputedStyle(img).objectFit})));if(new Set(photos.map(p=>p.src)).size!==photos.length)errors.push('home repeats a photograph');if(photos.some(p=>!p.alt||!p.src?.startsWith('/images/awake-bake/')))errors.push('missing alt or local image');if(photos.slice(1).some(p=>p.loading!=='lazy'))errors.push('non-hero images are not lazy');await page.goto(base+'/productos');const productSources=await page.locator('.catalog-grid img').evaluateAll(images=>images.map(img=>img.getAttribute('src')));if(new Set(productSources).size!==6)errors.push('product cards repeat photographs');await page.goto(base+'/');if(await page.locator('.gallery-tile').count()!==6)errors.push('gallery does not contain six photos');await page.close();
await browser.close();console.log(JSON.stringify({routes:routes.length,widths:[360,390,768,1024,1440],homePhotos:photos.length,productPhotos:productSources.length,reducedMotion:motion,errors},null,2));if(errors.length)process.exit(1);
